# Generated by Django 5.1.3 on 2026-04-20 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('contribution_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('flexible', 'Flexible')], max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lock_period_days', models.PositiveIntegerField(default=0)),
                ('commission_type', models.CharField(choices=[('fixed', 'Fixed'), ('first_contribution', 'First Contribution'), ('percentage', 'Percentage')], max_length=30)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_packages', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
                ('custom_contribution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_packages', to='tenants.tenant')),
                ('savings_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_packages', to='services.savingspackage')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='customers.customer')),
                ('customer_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='services.customerpackage')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('manual', 'Manual'), ('transfer', 'Transfer'), ('pos', 'POS'), ('ussd', 'USSD'), ('online', 'Online'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contributions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='customers.customer')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_requests', to='tenants.tenant')),
                ('customer_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='services.customerpackage')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='services_co_tenant__ed1ab3_idx'), models.Index(fields=['customer'], name='services_co_custome_f6619e_idx'), models.Index(fields=['customer_package'], name='services_co_custome_4ce7e5_idx'), models.Index(fields=['status'], name='services_co_status_98a155_idx'), models.Index(fields=['reference'], name='services_co_referen_629deb_idx'), models.Index(fields=['tenant', 'status'], name='services_co_tenant__4c0575_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='savingspackage',
            index=models.Index(fields=['tenant'], name='services_sa_tenant__a333c8_idx'),
        ),
        migrations.AddIndex(
            model_name='savingspackage',
            index=models.Index(fields=['is_active'], name='services_sa_is_acti_c449df_idx'),
        ),
        migrations.AddIndex(
            model_name='savingspackage',
            index=models.Index(fields=['contribution_type'], name='services_sa_contrib_724540_idx'),
        ),
        migrations.AddIndex(
            model_name='savingspackage',
            index=models.Index(fields=['tenant', 'is_active'], name='services_sa_tenant__e6c7ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='savingspackage',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_package_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='customerpackage',
            index=models.Index(fields=['tenant'], name='services_cu_tenant__83ace3_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpackage',
            index=models.Index(fields=['customer'], name='services_cu_custome_5851a4_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpackage',
            index=models.Index(fields=['savings_package'], name='services_cu_savings_acecf5_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpackage',
            index=models.Index(fields=['status'], name='services_cu_status_43fc67_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpackage',
            constraint=models.UniqueConstraint(fields=('customer', 'savings_package'), name='unique_customer_savings_package'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['tenant'], name='services_wi_tenant__99c7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['customer'], name='services_wi_custome_e2b501_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['customer_package'], name='services_wi_custome_c42387_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status'], name='services_wi_status_cc1dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['reference'], name='services_wi_referen_3a48f2_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['tenant', 'status'], name='services_wi_tenant__30929c_idx'),
        ),
    ]
