# Generated by Django 5.1.3 on 2026-04-24 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('entity_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('SAVINGS_PACKAGE', 'Savings Package'), ('CUSTOMER_PACKAGE', 'Customer Package'), ('CONTRIBUTION_REQUEST', 'Contribution Request'), ('WITHDRAWAL_REQUEST', 'Withdrawal Request'), ('TRANSACTION', 'Transaction')], max_length=50)),
                ('entity_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_role', models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('TENANT_ADMIN', 'Tenant Admin'), ('CUSTOMER', 'Customer'), ('AGENT', 'Agent')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='financials__tenant__df92bd_idx'), models.Index(fields=['user'], name='financials__user_id_b8299f_idx'), models.Index(fields=['action'], name='financials__action_df4b02_idx'), models.Index(fields=['entity_type'], name='financials__entity__a9ad5f_idx'), models.Index(fields=['created_at'], name='financials__created_597905_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('contribution', 'Contribution'), ('withdrawal', 'Withdrawal'), ('commission', 'Commission')], max_length=20)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='services.contributionrequest')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer')),
                ('customer_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.customerpackage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant')),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='services.withdrawalrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='financials__tenant__89e763_idx'), models.Index(fields=['customer'], name='financials__custome_0ea8e8_idx'), models.Index(fields=['customer_package'], name='financials__custome_7480c8_idx'), models.Index(fields=['transaction_type'], name='financials__transac_2c1abd_idx'), models.Index(fields=['entry_type'], name='financials__entry_t_570d29_idx'), models.Index(fields=['reference'], name='financials__referen_65cad7_idx'), models.Index(fields=['tenant', 'customer'], name='financials__tenant__6d54b1_idx')],
            },
        ),
    ]
