# Generated by Django 5.1.3 on 2026-04-20 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('nin', models.CharField(max_length=11, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('channel', models.CharField(choices=[('referral', 'Referral'), ('agent', 'Agent'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='referral', max_length=20)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='customers_c_tenant__9880e6_idx'), models.Index(fields=['user'], name='customers_c_user_id_c1d57c_idx'), models.Index(fields=['agent'], name='customers_c_agent_i_f2c20a_idx'), models.Index(fields=['status'], name='customers_c_status_ce44cf_idx'), models.Index(fields=['tenant', 'status'], name='customers_c_tenant__d5e64f_idx')],
            },
        ),
    ]
