# Generated by Django 5.1.3 on 2026-06-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=2341234567898, max_length=13),
            preserve_default=False,
        ),
    ]
